### ISSUE TITLE
Empty response while retrieving unassigned routes

### ISSUE THREAD

**Issue by imranhakeem** [rubyonrails3/school_transport-#2]
What is happening:
Getting empty response by passing "unassigned=true" parameter.
Response Code: 200[]

What should happen:
Should get the response like following example:

Example:
[{"id":"3","name":"Walatabad","bus_number":"12345","arrival_time":"2016-02-19 02:13:24","departure_time":"2016-02-19 05:13:24","start_latitude":"30.19780000","end_latitude":"71.46970000","start_longitude":"30.17615700","end_longitude":"71.45404800","total_stops":"10","driver":null}]

**Comment by rubyonrails3** [comment]
@imranhakeem  can you give it an other try I think I've just fixed it.

**Comment by imranhakeem** [comment]
Ok

Sent from Outlook Mobile

On Wed, Mar 9, 2016 at 11:39 AM -0800, "rubyonrails3" notifications@github.com wrote:

@imranhakeem  can you give it an other try I think I've just fixed it.

---
